### ISSUE TITLE
the \dedicatory  causes an error

### ISSUE THREAD

**Issue by ouboub** [jlelong/amsaddr#1]
Hi

I encountered a problem when using amsaddr in amsart articles, that include the 
\dedicatory command.

I attach a minimal example the log with the error and the patch by
curtousy of Ulrike Fischer. (https://www.troubleshooting-tex.de/)
(I can also provide a pull-request if you prefer that)

Thanks and regards

Uwe Brauer 

[Bug-Fix.zip](https://github.com/jlelong/amsaddr/files/9539808/Bug-Fix.zip)

**Comment by jlelong** [comment]
Thank you for the report and thanks to Ulrike Fischer for the fix.
I will push a new release to CTAN.
